[package]
name = "studyflow"
version = "1.4.0"
description = "StudyFlow - Study & TODO Tracker Desktop App"
authors = ["User"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "*", features = [] }

[dependencies]
tauri = { version = "*", features = [] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
